services:
  caddy:
    image: caddy:{{VERSION}}
    restart: unless-stopped
    networks:
      - caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./sites-enabled:/etc/caddy/sites-enabled:ro
      - ./data:/data
      - ./config:/config
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  caddy:
    external: true
