name: deploy whoami

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: install ship
        run: |
          go clean -modcache
          GOPROXY=direct go install github.com/markusylisiurunen/ship/cmd/ship@latest

      - name: configure domain
        run: sed -i 's/whoami.example.com/${{ secrets.WHOAMI_DOMAIN }}/' Caddyfile
        working-directory: ./whoami

      - name: ship whoami
        run: |
          ship deploy \
            --name whoami \
            --version $(git rev-parse --short HEAD) \
            --host ${{ secrets.WHOAMI_HOST }} \
            --password ${{ secrets.WHOAMI_PASSWORD }} \
            --volume hello-world
        working-directory: ./whoami
